<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_comment" class="required"><em>*</em><?php echo $this->__('Comment') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Commment') ?>" class="input-text required-entry" id="<?php echo $_code ?>_comment" name="payment[comment]" value="<?php echo $this->htmlEscape($this->getInfoData('comment')) ?>" />
        </span>
    </li>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
